# -*- coding: utf-8 -*-
"""Image pre processing

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-V9QEjOV39FmhbXJ5hyz7bkkuEC43n52

# ** BM Project Name: Real-Time Communication System Powered by AI for Specially Abled**
# **# TEAM ID:PNT2022TMID33509**
*Image Processing*
"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Training Datagen
train_datagen = ImageDataGenerator(rescale=1/255,zoom_range=0.2,horizontal_flip=True,vertical_flip=False)
# Testing Datagen
test_datagen = ImageDataGenerator(rescale=1/255)

import tensorflow as tf
import os
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, Dropout, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import matplotlib.pyplot as plt
import IPython.display as display
from PIL import Image
import pathlib

"""# **Apply ImageDataGenerator Functionality To Train And Test set**"""

from google.colab import drive

!unzip '/content/DATASET.zip'